version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: ./server/docker/dev.Dockerfile
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - fitno-app-network
    depends_on:
      - db
  db:
    image: mongo:6.0.6-jammy
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/lib/mongodb:/data/db
    networks:
      - fitno-app-network

networks:
  fitno-app-network:
    driver: bridge

volumes:
  node_modules:
  dbdata:

